---
title: "financials"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
```{r}
library(tidyverse)
library(rvest)
library(rjson)
library(jsonlite)
library(plyr)
library(dplyr)
library(data.table)
```


```{r}
getIncome <- function (ticker, format = "tidy", assign = TRUE) {
  
  scrape <- function (ticker) {
    df <- NULL
    attempt <- 0
    while(is.null(df) && attempt <= 3 ) {
      attempt <- attempt + 1
      try({
        url <- paste0("https://finance.yahoo.com/quote/",ticker,"/financials")
        page <- read_html(url)
        nodes <- page %>%html_nodes(".fi-row")
        
        for(i in nodes){
        r <- list(i %>%html_nodes("[title],[data-test='fin-col']")%>%html_text())
        df <- rbind(df,as.data.frame(matrix(r[[1]], ncol = length(r[[1]]), byrow = TRUE), stringsAsFactors = FALSE))
        }
        matches <- str_match_all(page%>%html_node('#Col1-3-Financials-Proxy')%>%html_text(),'\\d{1,2}/\\d{1,2}/\\d{4}')  
        headers <- c('Items','TTM', matches[[1]][,1]) 
        names(df) <- headers
        assign("df", df, pos = parent.frame())
      }, silent = TRUE)}
    
    ifelse(is.null(df),
           stop("After 3 attempts, no data was downloaded from yfinance. Either your ticker is wrong, or you have been downloading a lot of data and yfinance is blocking you."),
           return(df))
  }
  

  clean <- function (df) {
    df<- na_if(df,"-")
    df <- df %>%
       mutate_at(2:ncol(df), parse_number)
    
    df[17, 1] <- "Basic EPS"
    df[18, 1] <- "Diluted EPS"
    df[20, 1] <- "Basic W. Average Shares Outstanding"
    df[21, 1] <- "Diluted W. Average Shares Outstanding"
    
    df <- df %>% dplyr::filter(Items != "Operating Expenses" & Items != "Reported EPS"  & Items != "Weighted average shares outstanding")
    return(df)
  }
  
  
  tidy <- function (df) {
    df <- df %>% 
    pivot_longer(c(2:ncol(df)), names_to="date") %>% 
    pivot_wider(names_from = Items)
  
    substrEnd <- function(x, n){
    substr(x, nchar(x)-n+1, nchar(x))
    }
  
    df <- df %>% 
     mutate(ticker=toupper(ticker),
            year = substrEnd(date,4))
    
    df <- df %>% 
     select(ticker, date, year, everything())
    
  
    df <- df %>% dplyr::rename(
       "revenue"=`Total Revenue`,
       "cost_revenue" = `Cost of Revenue`,
       "gross_profit" = `Gross Profit`,
       "r&d" = `Research Development`,
       "sg&a" = `Selling General and Administrative`,
       "operating_expenses" = `Total Operating Expenses`,
       "ebit" = `Operating Income or Loss`,
       "interest_expense" = `Interest Expense`,
       "other_income_net" = `Total Other Income/Expenses Net`,
       "ebt" = `Income Before Tax`,
       "tax" = `Income Tax Expense`,
       "income_operations" = `Income from Continuing Operations`,
       "ni" = `Net Income`,
       "ni_to_shareholders" = `Net Income available to common shareholders`,
       "basic_eps" = `Basic EPS`,
       "diluted_eps" = `Diluted EPS`,
       "basic_w_avg_shares" = `Basic W. Average Shares Outstanding`,
       "diluted_w_avg_shares" = `Diluted W. Average Shares Outstanding`,
       "ebitda" = `EBITDA`
    )
    return(df)
  }
  
  if (assign != TRUE && assign != FALSE) stop("Assign can only be TRUE or FALSE.")
  
  
  if (format=="tidy") {
    result <- tidy(clean(scrape(ticker)))
    ifelse(assign == TRUE,
           assign(paste0(tolower(ticker),"_income"), result, envir = .GlobalEnv),
           return(result))
    
  } else if (format=="clean") {
    result <- clean(scrape(ticker))
    ifelse(assign == TRUE,
           assign(paste0(tolower(ticker),"_income_clean"), result, envir = .GlobalEnv),
           return(result))
    
  } else if (format=="raw") {
    result <- scrape(ticker)
    ifelse(assign == TRUE,
           assign(paste0(tolower(ticker),"_income_raw"), result, envir = .GlobalEnv),
           return(result))
    
  } else {
    stop('Format can only be "tidy", "clean", or "raw".')
  }
  
}
```



```{r}
getCashFlow <- function (ticker, format = "tidy", assign = TRUE) {
  
  scrape <- function (ticker) {
    df <- NULL
    attempt <- 0
    while(is.null(df) && attempt <= 3 ) {
      attempt <- attempt + 1
      try({
        url <- paste0("https://finance.yahoo.com/quote/",ticker,"/cash-flow")
        page <- read_html(url)
        nodes <- page %>%html_nodes(".fi-row")
        
        for(i in nodes){
        r <- list(i %>%html_nodes("[title],[data-test='fin-col']")%>%html_text())
        df <- rbind(df,as.data.frame(matrix(r[[1]], ncol = length(r[[1]]), byrow = TRUE), stringsAsFactors = FALSE))
        }
        matches <- str_match_all(page%>%html_node('#Col1-3-Financials-Proxy')%>%html_text(),'\\d{1,2}/\\d{1,2}/\\d{4}')  
        headers <- c('Items',"TTM", matches[[1]][,1]) 
        names(df) <- headers
        assign("df", df, pos = parent.frame())
      }, silent = TRUE)}
    
    ifelse(is.null(df),
           stop("After 3 attempts, no data was downloaded from yfinance. Either your ticker is wrong, or you have been downloading a lot of data and yfinance is blocking you."),
           return(df))
  }
  

  clean <- function (df) {
    df <- df %>% 
      dplyr::filter(Items != "Cash flows from operating activities"
                    & Items != "Cash flows from investing activities "
                    & Items != "Cash flows from financing activities")
    df <- df[-c(27),]
    df<- na_if(df,"-")
    df <- df %>%
       mutate_at(2:ncol(df), parse_number)
  }
  
  
  tidy <- function (df) {
    df <- df %>% 
      pivot_longer(c(2:ncol(df)), names_to="date") %>% 
      pivot_wider(names_from = Items)
    
    df <- df %>% 
      select(-`Operating Cash Flow`)
    
    df <- df %>% dplyr::rename(
      "ni" = `Net Income`,
      "da" = `Depreciation & amortization`,
      "deferred_taxes_change"=`Deferred income taxes`,
      "stock_comp" = `Stock based compensation`,
      "working_capital_change" = `Change in working capital`,
      "receivables_change" = `Accounts receivable`,
      "inventory_change" = `Inventory`,
      "payables_change" = `Accounts Payable`,
      "other_working_capital" = `Other working capital`,
      "other_non_cash" = `Other non-cash items`,
      "operating_cf" = `Net cash provided by operating activites`,
      "ppe_investment" = `Investments in property, plant and equipment`,
      "acquisitions" = `Acquisitions, net`,
      "purchases_investments" = `Purchases of investments`,
      "sales_investments" = `Sales/Maturities of investments`,
      "other_investing" = `Other investing activites`,
      "investing_cf" = `Net cash used for investing activites`,
      "debt_repayment" = `Debt repayment`,
      "stock_issued" = `Common stock issued`,
      "stock_repurchased" = `Common stock repurchased`,
      "dividends_paid" = `Dividends Paid`,
      "other_financing" = `Other financing activites`,
      "financing_cf" = `Net cash used privided by (used for) financing activities`,
      "change_cash" = `Net change in cash`,
      "cash_start_period" = `Cash at beginning of period`,
      "cash_end_period" = `Cash at end of period`,
      "capex" = `Capital Expenditure`,
      "fcf" = `Free Cash Flow`
    )
    substrEnd <- function(x, n){
    substr(x, nchar(x)-n+1, nchar(x))
    }
  
    df <- df %>% 
     mutate(ticker=toupper(ticker),
            year = substrEnd(date,4))
    
    df <- df %>% 
     select(ticker, date, year, everything())
    
    return(df)
  }
  
  if (assign != TRUE && assign != FALSE) stop("Assign can only be TRUE or FALSE.")

  if (format=="tidy") {
    result <- tidy(clean(scrape(ticker)))
    ifelse(assign == TRUE,
           assign(paste0(tolower(ticker),"_cf"), result, envir = .GlobalEnv),
           return(result))
    
  } else if (format=="clean") {
    result <- clean(scrape(ticker))
    ifelse(assign == TRUE,
           assign(paste0(tolower(ticker),"_cf_clean"), result, envir = .GlobalEnv),
           return(result))
    
  } else if (format=="raw") {
    result <- scrape(ticker)
    ifelse(assign == TRUE,
           assign(paste0(tolower(ticker),"_cf_raw"), result, envir = .GlobalEnv),
           return(result))
    
  } else {
    stop('Format can only be "tidy", "clean", or "raw".')
  }
  

}
```




```{r}
getBalanceSheet <- function (ticker, format="tidy", assign=TRUE) {
  
  scrape <- function (ticker) {
    df <- NULL
    attempt <- 0
    while(is.null(df) && attempt <= 3 ) {
      attempt <- attempt + 1
      try({
        url <- paste0("https://finance.yahoo.com/quote/",ticker,"/balance-sheet")
        page <- read_html(url)
        nodes <- page %>%html_nodes(".fi-row")
        
        for(i in nodes){
        r <- list(i %>%html_nodes("[title],[data-test='fin-col']")%>%html_text())
        df <- rbind(df,as.data.frame(matrix(r[[1]], ncol = length(r[[1]]), byrow = TRUE), stringsAsFactors = FALSE))
        }
        matches <- str_match_all(page%>%html_node('#Col1-3-Financials-Proxy')%>%html_text(),'\\d{1,2}/\\d{1,2}/\\d{4}')  
        headers <- c('Items', matches[[1]][,1]) 
        names(df) <- headers
        assign("df", df, pos = parent.frame())
      }, silent = TRUE)}
    
    ifelse(is.null(df),
           stop("After 3 attempts, no data was downloaded from yfinance. Either your ticker is wrong,   or you have been downloading a lot of data and yfinance is blocking you."),
           return(df))
  }

  clean <- function (df) {
    df <- df %>% 
      dplyr::filter(Items != "Assets"
                    & Items != "Current Assets"
                    & Items != "Cash"
                    & Items != "Non-current assets"
                    & Items != "Property, plant and equipment"
                    & Items != "Liabilities and stockholders' equity"
                    & Items != "Liabilities"
                    & Items != "Current Liabilities"
                    & Items != "Non-current liabilities"
                    & Items != "Stockholders' Equity")
    df<- na_if(df,"-")
    df <- df %>%
       mutate_at(2:ncol(df), parse_number)
  }

  
  tidy <- function (df) {
    df[21, 1] = "deferred_revenue_st"
    df <- df %>% 
      pivot_longer(c(2:ncol(df)), names_to="date") %>% 
      pivot_wider(names_from = Items)
    
    df <- df %>% dplyr::rename(
      "cash_equivalents" = `Cash And Cash Equivalents`,
      "st_investments" = `Short Term Investments`,
      "total_cash" = `Total Cash`,
      "net_receivables" = `Net Receivables`,
      "inventory" = `Inventory`,
      "other_ca" = `Other Current Assets`,
      "total_ca" = `Total Current Assets`,
      "gross_ppe" = `Gross property, plant and equipment`,
      "accumulated_depreciation" = `Accumulated Depreciation`,
      "net_ppe" = `Net property, plant and equipment`,
      "equity_other_investments" = `Equity and other investments`,
      "goodwill" = `Goodwill`,
      "intangibles" = `Intangible Assets`,
      "other_lta" = `Other long-term assets`,
      "total_lta" = `Total non-current assets`,
      "total_assets" = `Total Assets`,
      "total_revenue" = `Total Revenue`,
      "payables" = `Accounts Payable`,
      "taxes_payable" = `Taxes payable`,
      "accrued_liabilities" = `Accrued liabilities`,
      "other_cl" = `Other Current Liabilities`,
      "total_cl" = `Total Current Liabilities`,
      "lt_debt" = `Long Term Debt`,
      "deferred_taxes" = `Deferred taxes liabilities`,
      "deferred_revenue_lt" = `Deferred revenues`,
      "other_lt_liabilities" = `Other long-term liabilities`,
      "total_lt_liabilities" = `Total non-current liabilities`,
      "total_liabilities" = `Total Liabilities`,
      "common_stock" = `Common Stock`,
      "retained_earnings" = `Retained Earnings`,
      "accumulated_other_income" = `Accumulated other comprehensive income`,
      "total_equity" = `Total stockholders' equity`,
      "total_liabilities_equity" = `Total liabilities and stockholders' equity`
    )
    
    substrEnd <- function(x, n){
    substr(x, nchar(x)-n+1, nchar(x))
    }
  
    df <- df %>% 
    mutate(ticker=toupper(ticker),
            year = substrEnd(date,4))
    
    df <- df %>% 
     select(ticker, date, year, everything())
    
    return(df)
  }
  
    if (assign != TRUE && assign != FALSE) stop("Assign can only be TRUE or FALSE.")
  
    if (format=="tidy") {
      result <- tidy(clean(scrape(ticker)))
      ifelse(assign == TRUE,
             assign(paste0(tolower(ticker),"_bs"), result, envir = .GlobalEnv),
             return(result))
    } else if (format=="clean") {
      result <- clean(scrape(ticker))
      ifelse(assign == TRUE,
             assign(paste0(tolower(ticker),"_bs_clean"), result, envir = .GlobalEnv),
             return(result))
    } else if (format=="raw") {
      result <- scrape(ticker)
      ifelse(assign == TRUE,
             assign(paste0(tolower(ticker),"_bs_raw"), result, envir = .GlobalEnv),
             return(result))
    } else {
      stop('Format can only be "tidy", "clean", or "raw".')
    }
    
  
}
```





```{r}
getFinancials <- function (ticker, assign=TRUE) {
  l <- list()
  l[[1]]<- getIncome(ticker, format="tidy", assign=FALSE)
  l[[2]] <- getBalanceSheet(ticker, format="tidy", assign=FALSE)
  l[[3]] <- getCashFlow(ticker, format="tidy", assign=FALSE)
  result <- reduce(l, full_join, by = c("ticker", "date", "year")) %>% 
    select(-ni.y)
  result <- result %>% dplyr::rename(
    "ni" = `ni.x`
  )

  ifelse(assign==TRUE,
         assign(paste0(tolower(ticker), "_financials"), result, env=.GlobalEnv),
         return(result))
}
```

```{r}
getBalanceSheet("KO", "raw")
getCashFlow("KO", "raw")
```




```{r}
getIncomeMultiple <- function (tickers) {
  list <- lapply(X=tickers, FUN=getIncome)
  assign("income_statements", bind_rows(list), envir=.GlobalEnv)
}

getBalanceSheetMultiple <- function (tickers) {
  list <- lapply(X=tickers, FUN=getBalanceSheet)
  assign("balance_sheets", bind_rows(list), envir=.GlobalEnv)
}

getCashFlowMultiple <- function (tickers) {
  list <- lapply(X=tickers, FUN=getCashFlow())
  assign("cash_flows", bind_rows(list), envir=.GlobalEnv)
}
```





